@startuml ExprEngine

package XExprEngine
{
class ValueBase
{
    {abstract} +~ValueBase()=default;
    {abstract} +const typeinfo& type() const;
    {abstract} +string ToString() const;
    +bool IsNull() const;
}

class NullValue
{
    +NullValue();
    +const typeinfo& type() const override;
    +string ToString() const override;
}

class Value<T>
{
    +Value(T value);
    +Value(const Value<T>& value);
    +const typeinfo& type() const override;
    +string ToString() const override;
    +T value() const;
    -T value_;
}

class ExprValue
{
    +ExprValue();
    +ExprValue(const T&val);
    +ExprValue(const ExprValue& value) = default;
    +ExprValue& operator=(const ExprValue&) = default;
    +ExprValue(ExprValue&& value);
    +ExprValue& operator=(ExprValue&&);
    +ExprValue Clone() const;
    +static ExprValue Null();
    +bool IsNull() const;
    +const typeinfo& type() const;
    +string ToString() const;
    +T Cast() const;
    -shared_ptr<ValueBase> value_ptr_;
}

Value --|> ValueBase
NullValue --|> ValueBase
ExprValue *-- ValueBase

class ExprEngine
{
    +ExprEvalResult Evaluate(string expression_string, ExprContext* context = nullptr);
    +void SetCurrentContext()
    +ExprContext* current_context() const;
    -unordered_map<string, ExprContext> context_map_;
}

class ExprContext
{
    - unordered_map<string, Variable> variables_map_;
    - unordered_map<string, vector<string>> variable_adjacency_list_;
}

class Variable
{
    +Variable(string name);
    +Variable(string name, ExprValue value);
    +string name() const;
    +ExprValue value() const;
    +void Evaluate() const;
    -string name_;
    -ExprValue value_;
    -bool is_dirty_;
    -ExprContext* context_;
}

class ExprVariable
{
    +ExprVariable(string name, string expression_string);
    +string name() const;
    +string expression_string() const;
    -string name_;
    -string expression_string_;
}

ExprVariable --|> Variable
Variable *-- ExprValue
ExprContext *-- Variable
ExprEngine *-- ExprContext

class PyExprEngine

class PyExprContext

PyExprContext --|> ExprContext
PyExprEngine --|> ExprEngine

}

@enduml