// =============================================================================
//  python_loader.cc -- plugin execution + GIL-protected callback registry
// =============================================================================
//
//  Two responsibilities:
//
//    1. Plugin execution: run plugin files / code against an interpreter
//       that the HOST initialized.  Interpreter lifecycle (configuration,
//       initialization, finalization) lives in the python_manager static
//       library (src/python_manager) -- this translation unit never creates or
//       destroys an interpreter.
//
//    2. The GIL-protected callback registry: the ONLY place where pybind11::function
//       objects live.  Environment never sees a pybind11::function -- registered
//       Python functions become a pure-C++ shim whose impl_ captures a
//       std::string lookup key (see PYTHON.md sec.1 / sec.4).
// =============================================================================

#include "python_common.h"

#include "environment.h"

#include <pybind11/eval.h>

#include <algorithm>
#include <atomic>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace rel {
namespace python {
namespace {

// The GIL-protected callback registry.  Keys are unique ids generated by
// store_callback(); the shim captures only the key (a std::string).
std::unordered_map<std::string, pybind11::function> g_callbacks;

// Maps a registered function name -> its callback key, so that
// unregister_python_function / CleanupPythonState can release the pybind11::function.
std::unordered_map<std::string, std::string> g_name_to_key;

// Names of Python-registered functions, for ordered teardown.
std::vector<std::string> g_python_registered;

std::atomic<unsigned long long> g_next_key{0};

// The interpreter must have been initialized by the host before any plugin
// runs (python_manager::PyEnvManager::InitializePyEnv in main).
bool EnsureInterpreter(std::string* error_out)
{
    if (Py_IsInitialized())
        return true;
    if (error_out)
        *error_out = "Python interpreter not initialized; the host must call "
                     "python_manager::PyEnvManager::InitializePyEnv() first";
    return false;
}

// Make embedded stdout line-buffered so `print(...)` from Python plugins
// reaches the host's console immediately instead of being block-buffered
// until process exit.  Must run under the GIL.
bool g_stdout_configured = false;
void ConfigureStdout()
{
    if (g_stdout_configured)
        return;
    try
    {
        pybind11::exec("import sys\n"
                 "if hasattr(sys.stdout, 'reconfigure'):\n"
                 "    sys.stdout.reconfigure(line_buffering=True)\n");
    }
    catch (const pybind11::error_already_set&)
    {
        // Never let stdout configuration break plugin loading.
    }
    g_stdout_configured = true;
}

}  // namespace

bool LoadPythonFile(const std::string& path, std::string* error_out)
{
    if (!EnsureInterpreter(error_out))
        return false;

    pybind11::gil_scoped_acquire gil;
    ConfigureStdout();
    try
    {
        // Each plugin file gets an independent globals dict -- scripts cannot
        // pollute one another or the host __main__.
        pybind11::dict script_globals;
        script_globals["__builtins__"] = pybind11::module_::import("builtins");
        pybind11::eval_file(path, script_globals);
        return true;
    }
    catch (const pybind11::error_already_set& e)
    {
        if (error_out)
            *error_out = e.what();
        return false;
    }
}

bool ExecPythonCode(const std::string& code, std::string* error_out)
{
    if (!EnsureInterpreter(error_out))
        return false;

    pybind11::gil_scoped_acquire gil;
    ConfigureStdout();
    try
    {
        pybind11::dict script_globals;
        script_globals["__builtins__"] = pybind11::module_::import("builtins");
        pybind11::exec(code, script_globals);
        return true;
    }
    catch (const pybind11::error_already_set& e)
    {
        if (error_out)
            *error_out = e.what();
        return false;
    }
}

bool IsAvailable()
{
    // Compiled-in availability is indicated by this translation unit existing
    // at all; it always reports true when BUILD_PYTHON=ON.
    return true;
}

void CleanupPythonState()
{
    if (!Py_IsInitialized())
        return;

    pybind11::gil_scoped_acquire gil;  // destroying pybind11::function requires the GIL

    // Release Python-registered functions first (their shims hold no
    // pybind11::function, but the registry entries in Environment must go too).
    for (const auto& name : g_python_registered)
        Environment::UnregisterFunction(name);
    g_python_registered.clear();

    // Now drop all pybind11::function references (Py_DECREF) while the GIL is held.
    g_callbacks.clear();
    g_name_to_key.clear();

    // NOTE: the interpreter itself is NOT finalized here.  Finalization is
    // owned by python_manager (python_manager::PyEnvManager::ShutdownPyEnv),
    // which the host calls AFTER this cleanup.
}

std::string store_callback(pybind11::function fn)
{
    std::string key =
        "py_cb_" + std::to_string(g_next_key.fetch_add(1, std::memory_order_relaxed));
    g_callbacks.emplace(key, std::move(fn));
    return key;
}

NativeFunction make_callback_shim(const std::string& key)
{
    // The shim captures ONLY the key (std::string), so Function copy/move/dtor
    // never touch Python objects and never need the GIL (PYTHON.md sec.4.1).
    return [key](const Function::ArgMap& args) -> Value {
        pybind11::gil_scoped_acquire gil;  // re-entrant: harmless if already held

        auto it = g_callbacks.find(key);
        if (it == g_callbacks.end())
            throw std::runtime_error("python callback is no longer registered");

        pybind11::dict d;
        for (const auto& kv : args)
            d[pybind11::str(kv.first)] = to_python(kv.second);

        pybind11::object result = it->second(d);
        return from_python(result);
    };
}

void register_python_function(const std::string& name,
                              std::vector<FunctionParam> params,
                              pybind11::function fn)
{
    // Do NOT let a plugin silently shadow a builtin / C++-registered
    // function: Environment::RegisterFunction would overwrite it, which is
    // almost always a mistake.  Surface it as a Python-visible error instead.
    if (Environment::HasFunction(name))
        throw std::runtime_error(
            "cannot register Python function '" + name +
            "': a function with that name is already registered "
            "(builtin or C++); choose a different name");

    std::string key = store_callback(std::move(fn));
    g_name_to_key[name] = key;
    g_python_registered.push_back(name);

    Environment::RegisterFunction(
        Function(name, std::move(params), make_callback_shim(key)));
}

bool unregister_python_function(const std::string& name)
{
    // ALL registry containers (g_callbacks, g_name_to_key,
    // g_python_registered) are protected by the GIL -- every read/write must
    // happen under it, otherwise a concurrent register/unregister from
    // another thread is a data race on the containers themselves.
    {
        pybind11::gil_scoped_acquire gil;

        auto it = g_name_to_key.find(name);
        if (it == g_name_to_key.end())
            return false;

        g_callbacks.erase(it->second);  // Py_DECREF under the GIL
        g_name_to_key.erase(it);

        auto& names = g_python_registered;
        names.erase(std::remove(names.begin(), names.end(), name), names.end());
    }

    return Environment::UnregisterFunction(name);
}

}  // namespace python
}  // namespace rel

// =============================================================================
//  Environment Python API (real implementations, BUILD_PYTHON=ON only)
// =============================================================================

namespace rel {

bool Environment::LoadPython(const std::string& path)
{
    std::string error;
    bool ok = python::LoadPythonFile(path, &error);
    if (!ok && !error.empty())
    {
        // Preserve the Python traceback but surface it through the C++ layer.
        throw std::runtime_error("Python error: " + error);
    }
    return ok;
}

bool Environment::ExecPython(const std::string& code)
{
    std::string error;
    bool ok = python::ExecPythonCode(code, &error);
    if (!ok && !error.empty())
        throw std::runtime_error("Python error: " + error);
    return ok;
}

bool Environment::IsPythonAvailable()
{
    return python::IsAvailable();
}

void Environment::CleanupPythonState()
{
    python::CleanupPythonState();
}

}  // namespace rel
